### ISSUE TITLE
问题2

### ISSUE THREAD

**Issue by ccavxx** [nanshihui/Scan-T#6]
基于ubuntu安装的，按照wiki来安装的，导入数据库的时候出错了
ERROR 1128 (HY000): Function 'mysqlcft' is not defined

结果到最后就有下面的问题了
sqltool : ERROR    数据库错误(1146, "Table 'datap.snifferdata' doesn't exist")
sqltool : ERROR    数据库错误(1146, "Table 'datap.snifferdata' doesn't exist")
sqltool : ERROR    数据库错误(1146, "Table 'datap.snifferdata' doesn't exist")
sqltool : ERROR    数据库错误(1146, "Table 'datap.snifferdata' doesn't exist")
ERROR:sqltool:数据库错误(1146, "Table 'datap.snifferdata' doesn't exist")
error in elasticsearch No module named elasticsearch_dsl.query

请问怎么解决

**Comment by nanshihui** [comment]
mysqlcft 是数据库插件， 你可以百度插件安装就行

**Comment by ccavxx** [comment]
error in elasticsearch No module named elasticsearch_dsl.query  这个呢，弄了半天还是没搞定

**Comment by nanshihui** [comment]
更新到最新版 就没事了
