### ISSUE TITLE
安装成功，有关平台使用的问题

### ISSUE THREAD

**Issue by burnegg** [nanshihui/Scan-T#7]
在添加任务的时候怎么使用ip段呢？
我使用了cidr和-来表示，然后都扫描不出来结果。
然后我单个主机扫描的结果在首页也搜索不出来

**Comment by nanshihui** [comment]
ip段的功能接口都有，未添加到网页，晚些时候加进去;检索的话，使用的是mysql的全文检索+中文插件，以及es两种检索，请确保两者有一个已正确安装。
